version: '3'
services:
  db:
    user: root
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA= /pg-data
    container_name: ${DB_HOST}
    volumes:
      - pg-data:/pg-data
  nestjs:
    user: root
    build:
      context: .
      dockerfile: ./Dockerfile
    image: finess-app-server
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_SYNC=false
      - JWT_KEY=${JWT_KEY}
      - POSTGRES_PORT=${DB_HOST}
      - APP_PORT=${APP_PORT}
      - CLIENT_URL=${CLIENT_URL}
      - RECREATE_JWT_KEY=${RECREATE_JWT_KEY}
      - USER_PASS=${USER_PASS}
      - USER_MAIL=${USER_MAIL}
    ports:
      - '4200:3000'
    container_name: fitness-app-server
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  pgadmin:
    user: root
    image: dpage/pgadmin4
    restart: always
    container_name: fitness-app-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
      - POSTGRES_PASSWORD= ${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "4300:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  pg-data:
  pgadmin-data:
